TARGET_NAMES += config
TARGET_NAMES += genome_instrumentation
TARGET_NAMES += stratum_retention_strategy

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/test_include/MaketemplateForwarding.mak
