version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - pandoc
    - clang-19
  tools:
    python: "3.11"
  commands:
    - pip install -r requirements-dev/requirements-docs.txt
    - CC=clang-19 pip install . --no-deps
    - make -C docs/ html
    - mkdir -p _readthedocs
    - rm -rf _readthedocs/html
    - cp -r docs/_build/html _readthedocs/
