#pragma once
#ifndef HSTRAT_PYBIND_IMPL_PYOBJECTORDEREDSTORESHIMCONCEPT_FALSE_HPP_INCLUDE
#define HSTRAT_PYBIND_IMPL_PYOBJECTORDEREDSTORESHIMCONCEPT_FALSE_HPP_INCLUDE

namespace hstrat_pybind {

template<class T> concept PyObjectOrderedStoreShimConcept = false;

} // namespace hstrat_pybind

#endif // #ifndef HSTRAT_PYBIND_IMPL_PYOBJECTORDEREDSTORESHIMCONCEPT_FALSE_HPP_INCLUDE
