#pragma once
#ifndef HSTRAT_CONFIG_HSTRAT_RANK_T_HPP_INCLUDE
#define HSTRAT_CONFIG_HSTRAT_RANK_T_HPP_INCLUDE

#ifndef HSTRAT_RANK_T
#define HSTRAT_RANK_T int64_t
#endif // #ifndef HSTRAT_RANK_T

#endif // #ifndef HSTRAT_CONFIG_HSTRAT_RANK_T_HPP_INCLUDE
