#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_DEPTH_PROPORTIONAL_RESOLUTION_ALGO_SCRY_CALCNUMSTRATARETAINEDEXACTFTOR_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_DEPTH_PROPORTIONAL_RESOLUTION_ALGO_SCRY_CALCNUMSTRATARETAINEDEXACTFTOR_HPP_INCLUDE

namespace hstrat {
namespace depth_proportional_resolution_algo {

struct CalcNumStrataRetainedExactFtor {

  template<typename POLICY_SPEC>
  CalcNumStrataRetainedExactFtor(const POLICY_SPEC&) {}

  template<typename POLICY>
  void operator()(const POLICY& policy) const {

  }

};

} // namespace depth_proportional_resolution_algo
} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_DEPTH_PROPORTIONAL_RESOLUTION_ALGO_SCRY_CALCNUMSTRATARETAINEDEXACTFTOR_HPP_INCLUDE
