#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_FIXED_RESOLUTION_ALGO_INVAR_CALCNUMSTRATARETAINEDUPPERBOUNDFTOR_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_FIXED_RESOLUTION_ALGO_INVAR_CALCNUMSTRATARETAINEDUPPERBOUNDFTOR_HPP_INCLUDE

namespace hstrat {
namespace fixed_resolution_algo {

template<typename POLICY_SPEC>
struct X {

  X(const POLICY_SPEC& spec) {}

  template<typename POLICY>
  void operator()(const POLICY& policy) const {

  }

};

} // namespace fixed_resolution_algo
} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_STRATEGY_STRATUM_RETENTION_ALGORITHMS_FIXED_RESOLUTION_ALGO_INVAR_CALCNUMSTRATARETAINEDUPPERBOUNDFTOR_HPP_INCLUDE
