TEST_NAMES += include
TEST_NAMES += PyObjectConcept
TEST_NAMES += PyObjectIteratorShim
TEST_NAMES += PyObjectPolicyShim

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/test_include/MaketemplateRunning.mak
