#pragma once
#ifndef HSTRAT_GENOME_INSTRUMENTATION_INCLUDE_HPP_INCLUDE
#define HSTRAT_GENOME_INSTRUMENTATION_INCLUDE_HPP_INCLUDE

#include "HereditaryStratum.hpp"

#endif // #ifndef HSTRAT_GENOME_INSTRUMENTATION_INCLUDE_HPP_INCLUDE
