import typing
from typing import overload

def build_trie_from_artifacts_sync(
    population: typing.List[typing.Tuple[typing.List[int], typing.List[int]]],
    taxon_labels: typing.List[str],
) -> TrieInnerNode_C: ...

class TrieInnerNode_C:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rank: int, differentia: int) -> None: ...
    def __eq__(self, value: object, /) -> bool: ...
    @property
    def rank(self) -> int: ...
    @property
    def differentia(self) -> int: ...
    @property
    def inner_children(self) -> typing.List[TrieInnerNode_C]: ...
    @property
    def outer_children(self) -> typing.List[TrieInnerNode_C]: ...
    def InsertTaxon(
        self, ranks: typing.List[int], differentiae: typing.List[int]
    ) -> None: ...

class TrieLeafNode_C:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, taxon_label: str) -> None: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __gt__(self, value: object, /) -> bool: ...
    @property
    def taxon_label(self) -> str: ...
